
exports.seed = function(knex, Promise) {
  return Promise.join(
    // Deletes ALL existing entries
    knex('gallery').del(), 

    // Inserts seed entries
    knex('gallery').insert({id: 1, name: 'ankle', category: 'body', filepath: 'img/body/ankle.png'}),
    knex('gallery').insert({id: 2, name: 'back', category: 'body', filepath: 'img/body/back.png'}),
    knex('gallery').insert({id: 3, name: 'ear', category: 'body', filepath: 'img/body/ear.png'}),
    knex('gallery').insert({id: 4, name: 'head', category: 'body', filepath: 'img/body/head.png'}),
    knex('gallery').insert({id: 5, name: 'leg', category: 'body', filepath: 'img/body/leg.png'}),
    knex('gallery').insert({id: 6, name: 'afraid', category: 'emotions', filepath: 'img/emotions/afraid.png'}),
    knex('gallery').insert({id: 7, name: 'bad', category: 'emotions', filepath: 'img/emotions/bad.png'}),
    knex('gallery').insert({id: 8, name: 'cry', category: 'emotions', filepath: 'img/emotions/cry.png'}),
    knex('gallery').insert({id: 9, name: 'hate', category: 'emotions', filepath: 'img/emotions/hate.png'}),
    knex('gallery').insert({id: 10, name: 'laugh', category: 'emotions', filepath: 'img/emotions/laugh.png'}),
    knex('gallery').insert({id: 11, name: 'like', category: 'emotions', filepath: 'img/emotions/like.png'}),
    knex('gallery').insert({id: 12, name: 'bathe', category: 'home', filepath: 'img/home/bathe.png'}),
    knex('gallery').insert({id: 13, name: 'bathroom', category: 'home', filepath: 'img/home/bathroom.png'}),
    knex('gallery').insert({id: 14, name: 'bedTime', category: 'home', filepath: 'img/home/bedTime.png'}),
    knex('gallery').insert({id: 15, name: 'brushHair', category: 'home', filepath: 'img/home/brushHair.png'}),
    knex('gallery').insert({id: 16, name: 'brushTeeth', category: 'home', filepath: 'img/home/brushTeeth.png'}),
    knex('gallery').insert({id: 17, name: 'family1', category: 'home', filepath: 'img/home/family1.png'}),
    knex('gallery').insert({id: 18, name: 'toyTrain', category: 'home', filepath: 'img/home/toyTrain.png'}),
    knex('gallery').insert({id: 19, name: 'car', category: 'outside', filepath: 'img/outside/car.png'}),
    knex('gallery').insert({id: 20, name: 'leaf', category: 'outside', filepath: 'img/outside/leaf.png'}),
    knex('gallery').insert({id: 21, name: 'leave', category: 'outside', filepath: 'img/outside/leave.png'}),
    knex('gallery').insert({id: 22, name: 'trampoline', category: 'outside', filepath: 'img/outside/trampoline.png'}),
    knex('gallery').insert({id: 23, name: 'tree', category: 'outside', filepath: 'img/outside/tree.png'}),
    knex('gallery').insert({id: 24, name: 'apple', category: 'food', filepath: 'img/food/apple.png'}),
    knex('gallery').insert({id: 25, name: 'apricot', category: 'food', filepath: 'img/food/apricot.png'}),
    knex('gallery').insert({id: 26, name: 'bakedPotato', category: 'food', filepath: 'img/food/bakedPotato.png'}),
    knex('gallery').insert({id: 27, name: 'banana', category: 'food', filepath: 'img/food/banana.png'}),
    knex('gallery').insert({id: 28, name: 'pear', category: 'food', filepath: 'img/food/pear.png'}),
    knex('gallery').insert({id: 29, name: 'plums', category: 'food', filepath: 'img/food/plums.png'}),
    knex('gallery').insert({id: 30, name: 'watermelon', category: 'food', filepath: 'img/food/watermelon.png'}),
    knex('gallery').insert({id: 31, name: 'artClass1', category: 'school', filepath: 'img/school/artClass1.png'}),
    knex('gallery').insert({id: 32, name: 'circleTime', category: 'school', filepath: 'img/school/circleTime.png'}),
    knex('gallery').insert({id: 34, name: 'count', category: 'school', filepath: 'img/school/count.png'}),
    knex('gallery').insert({id: 35, name: 'lunchTime', category: 'school', filepath: 'img/school/lunchTime.png'}),
    knex('gallery').insert({id: 36, name: 'pencilSharpener', category: 'school', filepath: 'img/school/pencilSharpener.png'}),
    knex('gallery').insert({id: 37, name: 'eat2', category: 'verbs', filepath: 'img/verbs/eat2.png'}),
    knex('gallery').insert({id: 38, name: 'listen', category: 'verbs', filepath: 'img/verbs/listen.png'}),
    knex('gallery').insert({id: 39, name: 'see', category: 'verbs', filepath: 'img/verbs/see.png'}),
    knex('gallery').insert({id: 40, name: 'sick', category: 'verbs', filepath: 'img/verbs/sick.png'}),
    knex('gallery').insert({id: 41, name: 'smell', category: 'verbs', filepath: 'img/verbs/smell.png'}),
    knex('gallery').insert({id: 42, name: 'touch', category: 'verbs', filepath: 'img/verbs/touch.png'})
  );
};
